### ISSUE TITLE
http://esm.sh/balance-crypto not working

### ISSUE THREAD

**Issue by talentlessguy** [postui/esm.sh#65]
URL: http://esm.sh/balance-crypto

Error:

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "esbuild: No matching export in \"esm-build-5fbe66019deed45c715a316fc79902565cb5c540/node_modules/balance-crypto/dist/index.js\" for import \"default\"");
export default null;
```

Module dist/index.js file is an ESM file with one named export.

https://npmfs.com/package/balance-crypto/0.2.6/dist/index.js#L456

why would it break on no default export?

**Comment by ije** [comment]
thanks, i will look into it

**Comment by jaydenseric** [comment]
Same issue for a bunch of packages, for example:

https://esm.sh/graphql-react@15.0.0

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "esbuild: No matching export in \"esm-build-e616b5bc91d2d0be6c7e786ef2e81693615bfe0f/node_modules/graphql-react/public/index.mjs\" for import \"default\"");
export default null;
```

It's figuring out the right root module using `package.json` `exports` field:

https://github.com/jaydenseric/graphql-react/blob/v15.0.0/package.json#L37

But I don't know why it's attempting to make a default import from that file, since there is none:

https://unpkg.com/browse/graphql-react@15.0.0/public/index.mjs

**Comment by ije** [comment]
fixed in `v44` branch
