### ISSUE TITLE
antd do not work

### ISSUE THREAD

**Issue by fakership** [postui/esm.sh#70]
https://codesandbox.io/s/silly-blackwell-nm3qe?file=/index.html

if i use bundle antd and react to do a simple demo, react will throw an error

error:

![image](https://user-images.githubusercontent.com/16553183/120911846-03cfca00-c6bd-11eb-87e1-7821ff20862d.png)

https://reactjs.org/docs/error-decoder.html/?invariant=321

**Comment by fakership** [comment]
help!

**Comment by fakership** [comment]
@ije @asafamr @zhoukekestar @MarkTiedemann

**Comment by MarkTiedemann** [comment]
Hello @fakership.

Please don't tag random contributors in your issue. In general, people can voluntarily subscribe to the issues of a repository and will then receive a notification if a new issue is opened. I, for one, am not subscribed to this repository's issues - and just because I contributed to this repository once, I don't want to be notified about your issue. Again, in future, please don't tag random contributors.

Also, please don't scream for help 1h after opening an issue. I know coding can be frustrating, we've all had that experience before. But please understand that most people on GitHub contribute in their freetime, for fun. Putting pressure on random, well-meaning people on the internet so that they quickly help you with your issue is not a nice gesture.

Regarding your issue, I'd suggest adding the example code as well as the error message that you encountered in the description of this issue so that it is easier for anyone looking at this issue to understand your problem. At the same time, this may be helpful to other people in the future who encounter the same error message.

Have a good one! Hope your isssue is gonna be fixed soon.

**Comment by fakership** [comment]
I am so sorry for my incorrect tag

**Comment by MarkTiedemann** [comment]
@fakership Here's a minimal example of using `antd` via [esm.sh](https://esm.sh). It works just fine, there's no issue.

```html
<!DOCTYPE html>
<style>
	@import "https://esm.sh/antd@4.16.1/dist/antd.css";
</style>
<script type="module">
	import React from "https://esm.sh/react@17.0.2";
	import ReactDOM from "https://esm.sh/react-dom@17.0.2";
	import { Button } from "https://esm.sh/antd@4.16.1";

	ReactDOM.render(
		React.createElement(Button, { type: "primary" }, "Click me"),
		document.body
	);
</script>
```

**Comment by fakership** [comment]
thank you very much, the difference is i use the bundle antd,  which will bundle react in antd, which has conflict the outer react

**Comment by MarkTiedemann** [comment]
Okay. But that's not an issue with [esm.sh](https://esm.sh), but an issue with `antd`/`react`, right?

PS: There should be a "Close" button that you can use to close this issue, if it's fixed in your opinion.

**Comment by fakership** [comment]
done
